Vagrant.configure("2") do |config|
  config.vm.box = "win10"
  config.vm.hostname = "win10-analysis"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "win10-analysis-vm"
    vb.memory = 4096
    vb.cpus = 2
  end

  # Isolerat nätverk
  config.vm.network "private_network", type: "dhcp"

  # Ansible provisionering
  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "provision.yml"
  end
end
